name: tests
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read

defaults:
  run:
    working-directory: applications/pgdog

jobs:
  tests:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v6
      - name: Install CI deps
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_wait_seconds: 5
          command: cd applications/pgdog && bash integration/ci/install-deps.sh
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: applications/pgdog -> target
          prefix-key: "v1" # Change this when updating tooling
      - name: Setup PostgreSQL
        run: bash integration/ci/setup.sh --with-toxi
      - name: Run tests with coverage
        env:
          RUSTFLAGS: "--cfg tokio_unstable -C link-dead-code"
        run: |
          cargo llvm-cov clean --workspace
          cargo llvm-cov nextest --lcov --output-path lcov.info --no-fail-fast --test-threads=1 --filter-expr "package(pgdog) | package(pgdog-config) | package(pgdog-vector) | package(pgdog-stats) | package(pgdog-postgres-types)"
      - name: Run documentation tests
        run: cargo test --doc
      # Requires CODECOV_TOKEN secret for upload
      - uses: codecov/codecov-action@v4
        if: ${{ github.repository == 'pgdogdev/pgdog' && github.event_name != 'merge_group' }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: applications/pgdog/lcov.info
          flags: unit
          fail_ci_if_error: true
